### ISSUE TITLE
Name Too Long Error

### ISSUE THREAD

**Issue by dsssssssss9** [gurgleapps/image-to-code#2]
Hi

When i use the online encoder  to convert the following .png file....

![unnamed1](https://user-images.githubusercontent.com/30810847/149638054-cba3db11-c4ee-4ad3-9379-db1f9d49f491.png)

If i then import the base64 code into your example code.... by replacing the logo_large data with the data from above

[PICO_Gurgle_SH1106_Display Graphic_test1.txt](https://github.com/gurgleapps/image-to-code/files/7875921/PICO_Gurgle_SH1106_Display.Graphic_test1.txt)

 I get "RuntimeError: Name too long" error in thonny REPL
 
 Any clue as to what i am doing wrong would be appreciated!!

**Comment by mirkin** [comment]
Hi,

Try to put quotes around the string you get from the tool ''

Also a white background for your image rather than transparent, this won't cause an error but it won't show your image correctly being transparent.

**Comment by dsssssssss9** [comment]
Hi 

So grateful for such a quick reply ...

Have to get some shuteye as have to be up early in the morning for work but will try your advice as soon as I return home tomorrow evening ...

If you don't mind another cheeky question...

What would be the easiest way to convert my existing image to a non-transparent , white background. I have Gimp installed but am a super novice as to how to do anything more than convert image format with it ....

TTFN

**Comment by mirkin** [comment]
I've not used gimp for a long time, but in any package you should be able to draw white on a layer behind your transparent layer. We should really update the code to work with transparent images when we get a chance. 

I guess you could event load it in a web browser or image viewer and take a screen grab.

**Comment by bobby100** [comment]
![whiteBg](https://user-images.githubusercontent.com/16051732/149671567-b40e84a9-10e5-442c-8c20-810ec4bb7f8e.png)
Hi, Caleb here. I just put a white background on your image.

This is the Base64 Encoded string with the quotes. Let me know how you get on!

'gED///////////////////////////////////////////////////////////////////////////////////////wAAAAf//////gAAAA////8AAAAH//////4AAAAP////AAAAB//////+AAAAD///qgDnAByoAZUAM4AOcADf/4D////4AAAAAAH////wH/+A////+AAAAAAB////8B//gP////gAAAAAAf////Af/4D+AAP4D////wH8AAfwH/+A/gAD+A////8B/AAH8B//gP4AB/gP////AfwAB/Af/4D/5wf4D////wH+Dn/wH/+A////+A////8B////8B//gP////gP////Af////Af/4D////4D////wH////wH///AAAAB//////+AAAAD////wAAAAf//////gAAAA////8AAAAH//////4AAAAP//+qAOcAH///////gA5wAN//gP////////////////Af/4D////////////////wH/+A////////////////8B//gP4AAAAAAAAAAAAAB/Af/4D+AAAAAAAAAAAAAAfwH/+A/gAAAAAAAAAAAAAH8B//gP/nABzgA5wAc4AOf/Af/4D////////////////wH/+A////////////////8B//gP////////////////Af//8AAAAAAAAAAAAAAAAP////AAAAAAAAAAAAAAAAD////wAAAAAAAAAAAAAAAA////8AAQAc4AOcAHOACAAP////AAP///////////wAD////wAD///////////8AA////8AA////////////AAP//+A/gP///////////wH8B//gP4D///////////8B/Af/4D+A////////////AfwH/+A/+P8D/Af/4D/o/x/8B//gP//+AfwH/+A/gP///Af/4D///gH8B//gP4B///wH/+A///4B/Af/4D+Af//8B///wH/+AfwH/+A/gH/+A////8B//gH8B//gP4B//gP////Af/4B/Af/4D+A//4D///qgH/+AfwEZWA/gH/+ADf/4D///gH8AAAAP4D///wH/+A///4B/AAAAD+Af//8B//gP//+AfwAAAA/gH///Af/4AAAAP/8B//gP/8AAAAH/+AAAAD//Af/4D//AAAAB//gAAAB//wH/+A//wAAAAf/7gA5AAMqB//gDKgAnAB3/////wAAA////8AAAP////////8AAAP////AAAD/////////AAAD////wAAA//////////////////////////////////////////////////////////////////////////////////////////'

**Comment by dsssssssss9** [comment]
Hi 

so many thanks for doing this ...

a nice surprise to come home to after a long days work!!

please ignore the very slight corruption on the right of the screen - nothing to do with your code or conversion!! I hope to be able to find out what causes this & sort it soon



https://user-images.githubusercontent.com/30810847/149672971-147b63c0-824f-4d7f-940d-92e51ffc5b1a.mov



My thanks to the marvellous Gurgleapps team & not forgetting Mirkin for their help & support
